project:
  type: website
  output-dir: _site

website:
  title: "Shared Teaching Materials"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Materials
      - href: usage.qmd
        text: Usage
      - href: analytics/index.qmd
        text: Analytics

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    css: assets/styles.css

execute:
  freeze: auto

shared-materials: ".."
